from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(459, 257)
        Form.setStyleSheet("")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(160, 90, 151, 21))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.generar = QtWidgets.QPushButton(Form)
        self.generar.setGeometry(QtCore.QRect(350, 210, 91, 23))
        self.generar.setObjectName("generar")
        self.tableau = QtWidgets.QLabel(Form)
        self.tableau.setGeometry(QtCore.QRect(60, 90, 71, 21))
        self.tableau.setObjectName("tableau")
        self.admanager = QtWidgets.QLabel(Form)
        self.admanager.setGeometry(QtCore.QRect(60, 120, 91, 21))
        self.admanager.setObjectName("admanager")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(160, 120, 151, 21))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.cerrar = QtWidgets.QPushButton(Form)
        self.cerrar.setGeometry(QtCore.QRect(250, 210, 81, 23))
        self.cerrar.setObjectName("cerrar")
        self.cerrar.clicked.connect(self.close)
        self.publi = QtWidgets.QLabel(Form)
        self.publi.setGeometry(QtCore.QRect(99, 10, 251, 41))
        self.publi.setText("")
        self.publi.setObjectName("publi")
        self.background = QtWidgets.QLabel(Form)
        self.background.setGeometry(QtCore.QRect(0, -10, 1500, 843))
        self.background.setText("")
        self.background.setObjectName("background")
        self.mayus2 = QtWidgets.QLabel(Form)
        self.mayus2.setGeometry(QtCore.QRect(310, 110, 91, 21))
        self.mayus2.setText("")
        self.mayus2.setObjectName("mayus2")
        self.mayus1 = QtWidgets.QLabel(Form)
        self.mayus1.setGeometry(QtCore.QRect(330, 90, 91, 21))
        self.mayus1.setObjectName("mayus1")
        self.lineEdit_5 = QtWidgets.QLineEdit(Form)
        self.lineEdit_5.setGeometry(QtCore.QRect(160, 150, 151, 21))
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.datastudio = QtWidgets.QLabel(Form)
        self.datastudio.setGeometry(QtCore.QRect(60, 150, 101, 21))
        self.datastudio.setObjectName("datastudio")
        self.examinar = QtWidgets.QPushButton(Form)
        self.examinar.setGeometry(QtCore.QRect(330, 150, 71, 21))
        self.examinar.setObjectName("examinar")
        self.examinar.clicked.connect(self.search)
        self.status = QtWidgets.QLabel(Form)
        self.status.setGeometry(QtCore.QRect(60, 210, 191, 21))
        self.status.setText("")
        self.status.setObjectName("status")
        self.setWindowIcon(QtGui.QIcon('roboticon.ico'))
        self.publi.setPixmap(QtGui.QPixmap("publi_logo.png"))
        self.background.setPixmap(QtGui.QPixmap("background.png"))
        self.background.raise_()
        self.lineEdit.raise_()
        self.generar.raise_()
        self.tableau.raise_()
        self.admanager.raise_()
        self.lineEdit_2.raise_()
        self.cerrar.raise_()
        self.publi.raise_()
        self.mayus2.raise_()
        self.mayus1.raise_()
        self.lineEdit_5.raise_()
        self.datastudio.raise_()
        self.examinar.raise_()
        self.status.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.generar.setText(_translate("Form", "Generar reporte"))
        self.tableau.setText(_translate("Form", "Cuenta SF:"))
        self.admanager.setText(_translate("Form", "TO/Seller:"))
        self.cerrar.setText(_translate("Form", "Cerrar"))
        self.mayus1.setText(_translate("Form", "*mayúscula"))
        self.datastudio.setText(_translate("Form", "DataStudio reporte:"))
        self.examinar.setText(_translate("Form", "Examinar..."))

    def search(self):
        filename = QFileDialog.getOpenFileName(self, 'Open File')
        self.lineEdit_5.setText(filename[0])


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
